[tool.poetry]
name = "PROJECT_NAME"
version = "0.1.0"
description = ""
authors = ["AUTHOR <EMAIL>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
